In [6]:
import numpy as np

In [2]:
a=[1,2,3,4,5]
print(a)

[1, 2, 3, 4, 5]


In [5]:
#array=np.array([ele1,ele2,ele3....])
arr1D=np.array([1,2,3,4,5])       #1D Array
print(arr1D)

[1 2 3 4 5]


In [6]:
arr2D=np.array([[1,2,3],          #MultyDimensional Array
                [4,5,6],
                [7,8,9]])
print(arr2D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
#Default values in array or Zeroes in array
#np.zeros((shape))
zeroes_array=np.zeros((3))
zeroes_array3=np.zeros((3,3))

print(zeroes_array)
print(zeroes_array3)

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [18]:
#The Array full of once
#np.ones(shape)
ones3=np.ones((3,3))
ones=np.ones((3))

print(ones)
print(ones3)

[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [20]:
#To get a array full of random value
#np.full(shape,value)
array_5=np.full((3,3),5)
print(array_5)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [25]:
#creating sequences of numbers in array
#arange()
#arange(start,stop,step)

a=np.arange(0,11,2)
print(a)

[ 0  2  4  6  8 10]


In [32]:
#Identity Matrix
#np.eye(N)
identity_M=np.eye(5)
print(identity_M)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [40]:
#evenly spaced array
#np.linspace(start,stop,even_spaces)
Ls=np.linspace(1,10,6)
print(Ls)

[ 1.   2.8  4.6  6.4  8.2 10. ]


# Numpy Basics

In [49]:
#shape
#array_name.shape
arr_3d=np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(arr_3d.shape)

(3, 3)


In [50]:
#size
#array_name.size
print(arr_3d.size)

9


In [60]:
#ndim
#to check the no. of dimensions
#array.ndim
arr_1d=np.array([1,2,3])
arr_2d=np.array([[1,2,3],[4,5,6]])
arr_3d=np.array([[[[1,2],
                 [4,5],
                 [7,8],
                 [7,4]]]])

print(arr_1d.ndim)
print(arr_2d.ndim)
print(arr_3d.ndim)

1
2
4


In [61]:
#data type in array
#arr.dtype
print(arr_1d.dtype)

int32


In [66]:
#type conversion
#array.astype(new_type)
arr=np.array([1.2,2.3,3.4,4.5])
print(arr.dtype)
print(arr.astype(str))
print(arr.astype(int))

float64
['1.2' '2.3' '3.4' '4.5']
[1 2 3 4]


# Mathematical Operation

Operation                       syntax
+   + to add
+   - to substract
+   / to divided
+   '*' to multiply
+   % to check reminder
+   // Flore division
+   ** used for square
      




In [72]:
a=np.array([10,20,30,40,50])
print(a+5)
print(a*10)
print(a**2)
print(a/5)
print(a//5)
print(a%5)

[15 25 35 45 55]
[100 200 300 400 500]
[ 100  400  900 1600 2500]
[ 2.  4.  6.  8. 10.]
[ 2  4  6  8 10]
[0 0 0 0 0]


In [77]:
print(np.mean(a))
print(np.median(a))
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.std(a))
print(np.var(a))

30.0
30.0
150
10
50
14.142135623730951
200.0


# Indexing and Slicing

## numpy follows +ve indexing and -ve indexing

In [86]:
#slicing a[start,stop,step]

a=np.array([10,20,30,40,50,60,70,80,90,100])

print(a[0])
print(a[1])
print(a[-1])
print(a[0:11:2])
print(a[1:4])
print(a[0:])

10
20
100
[10 30 50 70 90]
[20 30 40]
[ 10  20  30  40  50  60  70  80  90 100]


# filtering Data

In [92]:
#Boolean Masking
#if condition is True will return True
#if condition is False it will return False

a=np.array([10,20,30,40,50,60,70,80,90,100])
print(a[a>25])
print(a[a<=50])

[ 30  40  50  60  70  80  90 100]
[10 20 30 40 50]


# Manipulating DATA

In [96]:
#reshape (row,column),if dimensions match. 
#flatten:-converts multidimensional array to one D array, it returns a copy     .flatten()
#ravel:- does the same thing as flatten but just returns a view                 .ravel()
b=np.array([[1,2,3],[4,5,6]])

print(b.reshape((3,2)))
print(b.flatten())
print(b.ravel())

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


# Reshaping and Modifying the array

In [117]:
#Inserting a value at a certain point in array
#np.insert(array,index,value,axis=0)
# axis 0=insert in row-wise
# axis 1=insert in cloumn-wise

man=np.array([1,2,3,4,5,6,7,8,9])
print(man)
man_n=np.insert(man,len(man),10)
print(man_n)



arr_2d=np.array([[1,2,3],[7,8,9]])
print(arr_2d)
# insert a new row at index 1
new_2d_arr=np.insert(arr_2d,1,[4,5,6] ,axis=0)
print(new_2d_arr)
new_2d_arr=np.insert(arr_2d,1,[4,5] ,axis=1)
print(new_2d_arr)



#append  np.append(array ,value)

new_man=np.append(man,[10,11,12])
print(new_man)

[1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[[1 2 3]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 2 3]
 [7 5 8 9]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [130]:
#concatenate  np.concatinate((arr1,arr2),axis=1)
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.concatenate((a,b))
print(c)

c1=np.delete(c,-1)
print(c1)

c2=np.array([[1,2,3],[4,5,6]])
print(np.delete(c2,0,axis=0))
print(np.delete (c2,0,axis=1))

[1 2 3 4 5 6]
[1 2 3 4 5]
[[4 5 6]]
[[2 3]
 [5 6]]


# stacking 

In [134]:
#vertical stack=vstack() row wise
#Horizontal stack=hstack() column wise
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(np.vstack((arr1,arr2))) #vertical stack
print(np.hstack((arr1,arr2))) #horizontal stack

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


# Split

In [148]:
"""
np.split()
equal

np.hsplit()
np.vsplit()
"""

arr1=np.array([1,2,3,4,5,6])
print(np.split(arr1,2))
print(np.split(arr1,3))
print(np.split(arr1,6))
arr2=np.array([[1,2,3],[4,5,6]])
print(np.vsplit(arr2,2))
print(np.hsplit(arr2,3))

[array([1, 2, 3]), array([4, 5, 6])]
[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]
[array([[1, 2, 3]]), array([[4, 5, 6]])]
[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


# Broadcasting and Vectorisation

In [155]:
prices=np.array([100,200,3000,400,5251])
discount=10  #10%

new_prices=[]
for price in prices:                                          ###to use a loop for big data set can take a lot of time so we use broadcasting
    new_price=price-(price * discount/100)
    new_prices.append(new_price)

print(new_prices)

[90.0, 180.0, 2700.0, 360.0, 4725.9]


In [161]:
prices=np.array([100,200,3000,400,5251])
discount=10  #10%

final_prices=prices -(prices* discount/100)
print(final_prices)


[  90.   180.  2700.   360.  4725.9]


In [165]:
#vectorization

list1=[1,2,3]
list2=[4,5,6]

result=[x+y for x,y in zip(list1,list2)]           #slow when working with big data
print(result)


list1=np.array([1,2,3])
list2=np.array([4,5,6])

result=list1+list2                                #fast when used with big amount of data
print(result)

multiply=list1*list2
print(multiply)

[5, 7, 9]
[5 7 9]
[ 4 10 18]


# Handling Missing Values

In [169]:
#np.isnan(array)
#used to detect the missingg vlues in array
arr=np.array([1,2,3,np.nan,5,6,np.nan])
print(np.isnan(arr))       #True means that the value is missing ,False means that the value is present 

cleaned_array=np.nan_to_num(arr) 
print(cleaned_array)


#np.isinf()

arr1=np.array([1,2,5,np.inf,8,-np.inf,4])
print(np.isinf(arr1))

clean_arr1=np.nan_to_num(arr1,posinf=1000,neginf=-1000)
print(clean_arr1)

[False False False  True False False  True]
[1. 2. 3. 0. 5. 6. 0.]
[False False False  True False  True False]
[    1.     2.     5.  1000.     8. -1000.     4.]


In [5]:
even_no=[x for x in range(1,51) if x%2==0]
print(even_no)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]


# Practice Question

In [13]:
even_no=np.arange(2,51,2)
print(even_no)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


In [18]:
arr=np.arange(1,13)
print(f'Original Array{arr}')
reshape=arr.reshape(3,4)
print(f'Rearranged{reshape}')

Original Array[ 1  2  3  4  5  6  7  8  9 10 11 12]
Rearranged[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [19]:
print(reshape.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [22]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(np.stack((arr1,arr2)))
print(np.vstack((arr1,arr2)))
print(np.hstack((arr1,arr2)))

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [25]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A*B)
print(A@B)

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [28]:
rand_num=np.random.randint(1,100,(3,3))
print(rand_num)

[[43 44 48]
 [40 85 98]
 [68 66 23]]


In [43]:
"""
Create an array of numbers from 1 to 20 and reshape it into a 4x5 matrix.

Extract the 2nd row and 3rd column element."""

arr=np.arange(1,21).reshape((4,5))
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [32]:
"""
Create two 2x2 matrices and:
Perform elementwise multiplication.
Perform matrix multiplication."""

A=np.array([[1,2],
            [4,5]])
B=np.array([[8,9],
            [5,6]])
print(A*B)
print(A@B)

[[ 8 18]
 [20 30]]
[[18 21]
 [57 66]]


In [39]:
"""Generate a 5x5 random matrix of integers (10–99).

Find the maximum, minimum, mean.

Flatten it into a 1D array."""
A=np.random.randint(10,99,(5,5))
print(A)
print(A.max())
print(A.min())
print(A.mean())
print(A.flatten())

[[93 34 20 18 59]
 [87 38 39 64 72]
 [94 90 36 54 56]
 [54 44 92 81 40]
 [97 87 98 63 26]]
98
18
61.44
[93 34 20 18 59 87 38 39 64 72 94 90 36 54 56 54 44 92 81 40 97 87 98 63
 26]


In [41]:
"""For matrix [[2,1],[7,4]]:
Find determinant, inverse, eigenvalues."""
A=np.array([[2,1],[7,4]])
det = np.linalg.det(A)
inv = np.linalg.inv(A)
eig_vals, eig_vecs = np.linalg.eig(A)
print("Determinant:", det)
print("Inverse:\n", inv)
print("Eigenvalues:", eig_vals)

Determinant: 0.9999999999999996
Inverse:
 [[ 4. -1.]
 [-7.  2.]]
Eigenvalues: [0.17157288 5.82842712]
